baseurl = "/"
title = "Wirchbench Blog"
theme = "ghostwriter"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "Wirchbench Notes"
    description = "Technical Notes Blog"
    github = "https://github.com/keithwirch/"
    #twitter = "https://twitter.com/XXX"
    #email = "XXX@example.com"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"
